# Generated by Django 5.2.17 on 2026-09-20 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('mode', models.CharField(choices=[('online', 'Online'), ('in_person', 'In person')], default='online', max_length=20)),
                ('is_published', models.BooleanField(default=False)),
            ],
        ),
    ]
